version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: alpine:latest
commands:
  image_build:
    steps:
    - run:
        name: Build Image
        command: |
          docker build -t ${FULL_IMAGE_NAME} .

jobs:
  build:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - image_build

  push:
    executor:
      name: default
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - image_build
    - run:
        name: Docker Hub login
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run:
        name: Push Docker Image
        command: |
          docker push ${FULL_IMAGE_NAME}

workflows:
  version: 2.1
  build-and-push:
    jobs:
    - build
    - push:
        requires:
        - build
