version: 2
jobs:
  "build":
    machine: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t ${FULL_IMAGE_NAME} .

  "push":
    machine: true
    steps:
      - run:
          name: Docker Hub login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker Image
          command: |
            docker push ${FULL_IMAGE_NAME}

workflows:
  - build-and-push:
    jobs:
      - build
      - push
