version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t ${FULL_IMAGE_NAME} .
      - run:
          name: Cache Image
          command: |
            mkdir -p ~/caches
            docker save ${FULL_IMAGE_NAME} -o ~/caches/images.tar
      - save_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar

  push:
    machine: true
    steps:
      - restore_cache:
          key: docker-{{ .Revision }}
          paths: ~/caches/images.tar
      - run:
          command: |
            set +o pipefail
            docker load -i ~/caches/images.tar | true
      - run:
          name: Docker Hub login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push Docker Image
          command: |
            docker push ${FULL_IMAGE_NAME}

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push:
          requires:
            - build
